defmodule Ex_Iso8583.TransactionTypeGroup do
  @moduledoc """
  DSL for defining grouped ISO 8583 transaction types with request-response pairs.

  This module allows you to define both request and response transaction types
  in a single module, keeping related transaction types together.

  ## Example

      defmodule SaleTransaction do
        use Ex_Iso8583.TransactionTypeGroup

        # Request definition (MTI 0100)
        defrequest mti: "0100", processing_code: "00*" do
          defstruct [
            :pan,
            :processing_code,
            :amount,
            :stan,
            :terminal_id,
            :merchant_id
          ]

          fields %{
            pan: 2,
            processing_code: 3,
            amount: 4,
            stan: 11,
            terminal_id: 41,
            merchant_id: 42
          }

          mandatory [:pan, :processing_code, :amount, :stan, :terminal_id, :merchant_id]
        end

        # Response definition (MTI 0110)
        defresponse mti: "0110", processing_code: "00*" do
          defstruct [
            :pan,
            :processing_code,
            :amount,
            :stan,
            :response_code
          ]

          fields %{
            pan: 2,
            processing_code: 3,
            amount: 4,
            stan: 11,
            response_code: 39
          }

          mandatory [:pan, :processing_code, :amount, :stan, :response_code]
        end
      end

  After defining a transaction group, you can use it:

      # Parse a request
      case SaleTransaction.Request.parse_and_validate(iso_msg, msg_type, field_format) do
        {:ok, request} -> IO.puts("Amount: " <> inspect(request.amount))
        {:error, reason} -> IO.puts("Validation failed: " <> inspect(reason))
      end

      # Parse a response
      case SaleTransaction.Response.parse_and_validate(iso_msg, msg_type, field_format) do
        {:ok, response} -> IO.puts("Response code: " <> inspect(response.response_code))
        {:error, reason} -> IO.puts("Validation failed: " <> inspect(reason))
      end

      # Find the pair module
      SaleTransaction.request_module()  # => SaleTransaction.Request
      SaleTransaction.response_module() # => SaleTransaction.Response
      SaleTransaction.find_pair(:request)  # => {:ok, SaleTransaction.Request}
      SaleTransaction.find_pair(:response) # => {:ok, SaleTransaction.Response}
      SaleTransaction.find_pair("0110", "00*")  # => {:ok, SaleTransaction.Response}
  """

  @doc """
  Defines a request transaction type.

  Creates a nested `Request` module within the parent module that uses
  `Ex_Iso8583.TransactionType` for the actual transaction type definition.

  ## Options
    - `:mti` - Message Type Indicator (required)
    - `:processing_code` - Processing code pattern (optional, defaults to "*")

  ## Example

      defrequest mti: "0100", processing_code: "00*" do
        defstruct [:pan, :amount]
        fields %{pan: 2, amount: 4}
        mandatory [:pan, :amount]
      end
  """
  defmacro defrequest(opts, do: block) do
    {mti, proc_code_pattern} = parse_request_opts(opts)

    quote do
      defmodule Request do
        @moduledoc """
        Request transaction type.

        This module is auto-generated by the TransactionTypeGroup DSL.
        """
        use Ex_Iso8583.TransactionType

        transaction_type unquote(mti), processing_code: unquote(proc_code_pattern) do
          unquote(block)
        end
      end
    end
  end

  defmacro defrequest(do: _block) do
    raise ArgumentError,
      "defrequest requires mti option, e.g., defrequest mti: \"0100\" do ... end"
  end

  @doc """
  Defines a response transaction type.

  Creates a nested `Response` module within the parent module that uses
  `Ex_Iso8583.TransactionType` for the actual transaction type definition.

  ## Options
    - `:mti` - Message Type Indicator (required)
    - `:processing_code` - Processing code pattern (optional, defaults to "*")

  ## Example

      defresponse mti: "0110", processing_code: "00*" do
        defstruct [:pan, :amount, :response_code]
        fields %{pan: 2, amount: 4, response_code: 39}
        mandatory [:pan, :amount, :response_code]
      end
  """
  defmacro defresponse(opts, do: block) do
    {mti, proc_code_pattern} = parse_request_opts(opts)

    quote do
      defmodule Response do
        @moduledoc """
        Response transaction type.

        This module is auto-generated by the TransactionTypeGroup DSL.
        """
        use Ex_Iso8583.TransactionType

        transaction_type unquote(mti), processing_code: unquote(proc_code_pattern) do
          unquote(block)
        end
      end
    end
  end

  defmacro defresponse(do: _block) do
    raise ArgumentError,
      "defresponse requires mti option, e.g., defresponse mti: \"0110\" do ... end"
  end

  # Parse options for defrequest/defresponse
  defp parse_request_opts(opts) do
    mti = Keyword.get(opts, :mti)
    proc_code = Keyword.get(opts, :processing_code, "*")

    unless mti do
      raise ArgumentError, "mti option is required"
    end

    {mti, proc_code}
  end

  @doc """
  Generates helper functions for the transaction group module.

  This is called via `@before_compile` to generate functions that reference
  the Request and Response submodules.
  """
  defmacro __before_compile__(env) do
    module_name = env.module

    quote do
      @doc """
      Returns the Request module for this transaction group.

      ## Example

          SaleTransaction.request_module()  # => SaleTransaction.Request
      """
      def request_module, do: unquote(Module.concat(module_name, Request))

      @doc """
      Returns the Response module for this transaction group.

      ## Example

          SaleTransaction.response_module()  # => SaleTransaction.Response
      """
      def response_module, do: unquote(Module.concat(module_name, Response))

      @doc """
      Finds a transaction type module by kind, or by MTI and processing code.

      ## Parameters
        - `:request` - Returns the Request module
        - `:response` - Returns the Response module
        - `mti, processing_code` - Finds the module that matches the MTI and processing code

      ## Returns
        - `{:ok, module}` - If a matching module is found
        - `{:error, :no_match}` - If no matching module is found
        - `{:error, :not_defined}` - If the requested kind is not defined

      ## Examples

          SaleTransaction.find_pair(:request)  # => {:ok, SaleTransaction.Request}
          SaleTransaction.find_pair(:response) # => {:ok, SaleTransaction.Response}
          SaleTransaction.find_pair("0100", "00*")  # => {:ok, SaleTransaction.Request}
          SaleTransaction.find_pair("0110", "00*")  # => {:ok, SaleTransaction.Response}
      """
      def find_pair(:request) do
        request_module = request_module()
        if Code.ensure_loaded?(request_module) do
          {:ok, request_module}
        else
          {:error, :not_defined}
        end
      end

      def find_pair(:response) do
        response_module = response_module()
        if Code.ensure_loaded?(response_module) do
          {:ok, response_module}
        else
          {:error, :not_defined}
        end
      end

      def find_pair(mti, processing_code) do
        request_module = request_module()
        response_module = response_module()

        # Try request first
        cond do
          Code.ensure_loaded?(request_module) and
            function_exported?(request_module, :mti, 0) and
            function_exported?(request_module, :matches?, 2) and
            request_module.mti() == mti and
            Ex_Iso8583.TransactionType.matches_pattern?(
              request_module.processing_code_pattern(),
              processing_code
            ) ->
            {:ok, request_module}

          Code.ensure_loaded?(response_module) and
            function_exported?(response_module, :mti, 0) and
            function_exported?(response_module, :matches?, 2) and
            response_module.mti() == mti and
            Ex_Iso8583.TransactionType.matches_pattern?(
              response_module.processing_code_pattern(),
              processing_code
            ) ->
            {:ok, response_module}

          true ->
            {:error, :no_match}
        end
      end

      @doc """
      Parses and validates a message by trying both request and response types.

      Since the ISO message doesn't include MTI when formed with `form_iso_msg/3`,
      this function tries to parse with both Request and Response modules.

      ## Returns
        - `{:ok, {:request, struct}}` - Successfully parsed as request
        - `{:ok, {:response, struct}}` - Successfully parsed as response
        - `{:error, reason}` - Validation or parsing failed

      ## Example

          case SaleTransaction.parse(iso_msg, msg_type, field_format) do
            {:ok, {:request, req}} -> IO.puts("Request amount: " <> inspect(req.amount))
            {:ok, {:response, resp}} -> IO.puts("Response code: " <> inspect(resp.response_code))
            {:error, reason} -> IO.puts("Parse failed: " <> inspect(reason))
          end
      """
      def parse(iso_msg, msg_type, field_format, opts \\ []) do
        # Try request first, then response
        request_module = request_module()
        response_module = response_module()

        parsed_result =
          cond do
            Code.ensure_loaded?(request_module) and
              function_exported?(request_module, :parse_and_validate, 4) ->
              case request_module.parse_and_validate(iso_msg, msg_type, field_format, opts) do
                {:ok, struct} -> {:ok, {:request, struct}}
                {:error, _} -> :try_next
              end

            true ->
              :try_next
          end

        if parsed_result == :try_next do
          if Code.ensure_loaded?(response_module) and
             function_exported?(response_module, :parse_and_validate, 4) do
            case response_module.parse_and_validate(iso_msg, msg_type, field_format, opts) do
              {:ok, struct} -> {:ok, {:response, struct}}
              {:error, reason} -> {:error, reason}
            end
          else
            {:error, :no_module_defined}
          end
        else
          parsed_result
        end
      end

      @doc """
      Returns all transaction type modules in this group.

      ## Example

          SaleTransaction.transaction_modules()
          # => [SaleTransaction.Request, SaleTransaction.Response]
      """
      def transaction_modules do
        modules = []

        modules =
          if Code.ensure_loaded?(request_module()) do
            [request_module() | modules]
          else
            modules
          end

        modules =
          if Code.ensure_loaded?(response_module()) do
            [response_module() | modules]
          else
            modules
          end

        Enum.reverse(modules)
      end
    end
  end

  defmacro __using__(_opts) do
    quote do
      import Ex_Iso8583.TransactionTypeGroup
      @before_compile Ex_Iso8583.TransactionTypeGroup
    end
  end
end
