name: hello-world
on: push
jobs:
  my-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24'
          elixir-version: '1.14.4'
      - uses: potatoqualitee/mssqlsuite@v1.7
        with:
          install: sqlengine, sqlpackage
      - run: mix deps.get
      - run: mix test
      - run: sqlcmd -S localhost -U sa -P dbatools.I0 -d tempdb -Q "SELECT @@version;"
